### ISSUE TITLE
why JavaScript?

### ISSUE THREAD

**Issue by childeofentropy** [huntzinger92/aPeoplesCalendarWeb#1]
Hi! great idea for a webpage, and thanks for being open-source.
I have a question and a suggestion:
why should JavaScript need to be enabled to access the page?
would you be interested in launching a plain text or a blocked-Java friendly version?

Thank you in advance.

**Comment by huntzinger92** [comment]
Unfortunately, ReactJS doesn't work without JavaScript enabled, and the entire logic/structure of the application is built around React's component composition and use of state. In this case, developing for JS-disabling users would seem to involve completely re-writing the application, and I'm not open to it right now.

That being said, I am planning on moving the event library to an actual database (currently just a JSON file). I was going to do it locally with sqlite, but if I add a remote back-end and start delivering the content remotely, I will keep this concern in mind. Thanks for reaching out.

**Comment by childeofentropy** [comment]
Thank for the response. The idea of a json file is even better! Not many people disable javascript in browsers and possible offline access should be more interesting and useful. Keep it up 😄😄

**Comment by childeofentropy** [comment]
just noticed that you said you already have the json file. is this file available? cause it could easily be imported in thunderbird or other calendar

**Comment by huntzinger92** [comment]
Yes. Check eventLibrary.js in either repository. Let me know how it imports, the data structure is probably pretty idiosyncratic.
________________________________
