### ISSUE TITLE
Use material-ui components for date and search query input on calendar page

### ISSUE THREAD

**Issue by huntzinger92** [huntzinger92/aPeoplesCalendarWeb#12]
When viewing apeoplescalendar.org/calendar, the input styling is a bit clunky (thanks to yours truly).

![Screenshot 2021-10-26 141834](https://user-images.githubusercontent.com/42256116/138946576-c2cb122e-4ace-4d4a-a30c-5bbbc065c8af.jpg)

The inputs would look sleeker and be more customizable by using a material-ui date picker and text input. The year input on the date picker is also not necessary, not sure if this possible to remove with material-ui customization or not.

Switching these over would also allow us to get rid of some of the bloated CSS.

**Comment by amelv** [comment]
#26 Seems like the PR fixed this issue, right?

**Comment by huntzinger92** [comment]
Yep, you're right!
