### ISSUE TITLE
Build out contact form

### ISSUE THREAD

**Issue by huntzinger92** [huntzinger92/aPeoplesCalendarWeb#15]
Right now, clicking the mail icon on the right-hand side of the navigation bar opens the user's preferred email application.

![Screenshot (214)_LI](https://user-images.githubusercontent.com/42256116/138948812-d104bb21-2bc1-4c2c-b52a-93ad69ceae46.jpg)

What would be preferable is building out a contact form that can be submitted from the website itself. I'm thinking it could another nav bar option: right next to "Calendar", there would be a "Contact".

Netlify has infrastructure we can leverage to do this, you can read instructions from their devs on how to do with React [here](https://www.freecodecamp.org/news/how-to-add-a-netlify-form-to-a-react-app/). On submit, it would send their input to apeoplescalendar@gmail.com

**Comment by queenofthelosers** [comment]
Could you test the latest PR?

**Comment by huntzinger92** [comment]
Hey, sorry, I got really busy this weekend with other work. Give me a few days to test it out, I should be able to approve it this week.

**Comment by huntzinger92** [comment]
Great work!
